### ISSUE TITLE
Possible race conditions in all Mandelbrot demos

### ISSUE THREAD

**Issue by cosinusoidally** [lars-t-hansen/parlib-simple#26] opened 2015-03-02 15:27 UTC
I've had a play with all 3 Mandelbrot demos with Nightly on Linux. I've noticed that the demos will occasionally stop animating (earlier than they should do, the status line never appears). A page reload usually fixes the problem.

With demo/mandelbrot-animation is assume I might be hitting the issue explained in https://github.com/lars-t-hansen/parlib-simple/blob/master/src/asymmetric-barrier.js#L97 . But unfortunately this particular demo has only frozen once for me, and I didn't have the foresight to type barrier.release() in the console to see whether that is why it was stuck.

**Comment by lars-t-hansen** [comment] 2015-03-03 09:50
Thanks, I'll take a look.

**Comment by lars-t-hansen** [comment] 2015-03-03 10:21
I think there's a race in the barrier implementation.  Specifically if the futexWait in enter() happens between the add and the futexWake in release(), and thus the waker falls through the Wake, if the worker gets to run an entire iteration and re-enter the barrier then the barrier will be in an inconsistent state. That is not terribly unlikely if a worker has a small or fast slice to work on, since the master will likely be suspended by the OS while it's waiting for the lock inside futexWake.

The code should have a couple of assertions I think: WorkerBarrier.enter should check that the counter value is greater than or equal to zero, and in MasterBarrier.release the quiescence test should really throw an error on failure.  Clients that don't want that can catch the error or perform an explicit quiescence test before the release.

**Comment by lars-t-hansen** [comment] 2015-03-03 11:26
I can reproduce the hang with the SIMD demo on my 4x2 MBP with 8 workers.  However, even with added checks for inconsistent state in the barrier, I see no error messages in the console, and I suspect it's something else, like a lost wakeup.  There is a suspected intermittent bug (https://bugzil.la/1137465) that occurs even without the asymmetric-barrier, looks more like a lost wakeup.  It could be related.

**Comment by lars-t-hansen** [comment] 2015-05-13 13:24
There was a lost wakeup bug in the futex implementation, which has been fixed (and the fix will be in Firefox Nightly as of the next merge, presumably tonight).  I am no longer able to reproduce the problem with an animation that stops.

**Comment by lars-t-hansen** [comment] 2015-06-08 20:54
Belived fixed.

**Closed by lars-t-hansen** 2015-06-08 20:54 UTC
Labels: bug, High priority
